### ISSUE TITLE
Tutorial about usage? Condition not working

### ISSUE THREAD

**Issue by nasiri** [CodersCare/device#2]
Hello dear Team,

i have a Problem using the conditions from your extension.
I just used it like this 

```
[device(“Mobile”)]
styles.content.textmedia.maxW = 590
styles.content.textmedia.maxWInText = 590
[ELSE]
styles.content.textmedia.maxW = 950
styles.content.textmedia.maxWInText = 950
[END]
```

But its somehow not working.
I am on T3 10.4

Thx for the help. Greetings from germany.

**Comment by Bunnyfield** [comment]
What exactly is not working and which of the values do you get?
And could you please post the whole code of your setup?
Sometimes problems are caused by conditions inside braces, which is not supposed to be working in TYpoScript.

**Comment by nasiri** [comment]
its completly ignored. the syntax is right thou? 

i need the conditions to use an alternative template and css file, until i move the template to a "responsive" one.
more or less its for replacing the userfunc = ismobile ...

```
# config.contentObjectExceptionHandler = 0
config.sys_language_uid = 0
config.doctype = html5 
config.language = de
config.locale_all = de_DE.UTF-8
config.htmlTag_langKey = de
config.linkVars = L(int)
config.sys_language_mode = content_fallback: 1,0

config.baseurl = https://www.xxx.com/
config.absRefPrefix = https://www.xxx.com/

config.pageTitleProviders {
   seo {
      provider = TYPO3\CMS\Seo\PageTitle\SeoTitlePageTitleProvider
   }
}
########### FOOTER ##########
lib.footer = CONTENT
lib.footer {
table = tt_content
wrap = <div class="container">|</div>
select {
pidInList = 115
begin = 0
languageField=sys_language_uid
select.where.field = colPos
select.where.wrap = colPos = |
}
}

########### FLUID TEMPLATE ##########

page.10 = FLUIDTEMPLATE
page.meta.keywords.data = levelfield:-1, keywords
page.meta.author.data = levelfield:-1, author
page.meta.description.data = levelfield:-1, description
page.meta.robots = index,follow

[device(“Mobile”)]
page.10 {
  file = fileadmin/src/tmpl/airscreen_mobile.html
}
[ELSE]
page.10 {
  file = fileadmin/src/tmpl/airscreen_neu_breit.html
}
[END]
  
# Default PAGE object:
page = PAGE
page.typeNum = 0

[device(“Mobile”)]
page.includeCSS {
        file1 = fileadmin/src/css/xxx.css
  		file1.external = 1
}
[ELSE]
page.includeCSS {
        file1 = fileadmin/src/css/xxx_desktop.css
  		file1.external = 1
}
[END]
```

**Comment by Bunnyfield** [comment]
"Completely ignored" means - you get nothing or you get the values of the ELSE part?

If you get the ELSE part, the problem might be that your testing device gets not recognised as "Mobile" - so what are you using to test the condition?

BTW: You should change the order of the code for better readability and combine the two conditions into one.
To skip the ELSE part, you should put those values in the default configuration and use the condition at the end of all code blocks to change those default values.

**Comment by nasiri** [comment]
yes. only the else part is recognized. but i use an iphone to check the mobile version. so that should work or gets recognized?!

i changed the condition part and put it at the end of the code.
no changes yet in the result.

```
page.10 {
  file = fileadmin/src/tmpl/xxx_neu_breit.html
}
page.includeCSS {
        file1 = fileadmin/src/css/style_xxx_neu_breit.css
  		file1.external = 1
}

[device(“Mobile”)]
page.10 {
  file = fileadmin/src/tmpl/xxx_mobile.html
}
page.includeCSS {
        file1 = fileadmin/src/css/style_xxx_mobile.css
  		file1.external = 1
}
[END]
```

**Comment by Bunnyfield** [comment]
Looks correct so far - so could you check with another device or by switching the condition to something else just to make sure that the detector itself is working? Maybe a look into the error log helps too.

**Comment by nasiri** [comment]
i got it working with replacing the [device(“Mobile”)] with [device("Smartphone")].

Thx a lot ;)

**Comment by Bunnyfield** [comment]
So the isMobile function of the Matomo Detector might be broken - will check that with their tracker now. Thanks for the feedback.
